-- 1. Automatic Timestamp Trigger
create or replace function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- 2. Estado Table
create table public.estado (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create trigger update_estado_updated_at
  before update on public.estado
  for each row execute function public.update_updated_at_column();

-- 3. Municipio Table
create table public.municipio (
  id bigint generated by default as identity primary key,
  nombre text not null,
  estado_id bigint references public.estado(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (nombre, estado_id)
);

create trigger update_municipio_updated_at
  before update on public.municipio
  for each row execute function public.update_updated_at_column();

-- 4. Parroquia Table
create table public.parroquia (
  id bigint generated by default as identity primary key,
  nombre text not null,
  municipio_id bigint references public.municipio(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (nombre, municipio_id)
);

create trigger update_parroquia_updated_at
  before update on public.parroquia
  for each row execute function public.update_updated_at_column();

-- 5. Categoria Table
create table public.categoria (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create trigger update_categoria_updated_at
  before update on public.categoria
  for each row execute function public.update_updated_at_column();

-- 6. Subcategoria Table
create table public.subcategoria (
  id bigint generated by default as identity primary key,
  nombre text not null,
  categoria_id bigint references public.categoria(id) on delete restrict not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (nombre, categoria_id)
);

create trigger update_subcategoria_updated_at
  before update on public.subcategoria
  for each row execute function public.update_updated_at_column();

-- 7. Institucion Table
create table public.institucion (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  direccion text not null,
  parroquia_id bigint references public.parroquia(id) on delete restrict not null,
  organizacion text,
  telefono text,
  horario text,
  tipos_ayuda text,
  notas text,
  instagram text,
  latitud double precision,
  longitud double precision,
  activo boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create trigger update_institucion_updated_at
  before update on public.institucion
  for each row execute function public.update_updated_at_column();

-- 8. Tipo Movimiento Table
create table public.tipo_movimiento (
  id bigint generated by default as identity primary key,
  nombre text not null unique, -- E.g., 'Entrada', 'Salida', 'Transferencia'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create trigger update_tipo_movimiento_updated_at
  before update on public.tipo_movimiento
  for each row execute function public.update_updated_at_column();

-- 9. Producto Table
create table public.producto (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  presentacion text, -- E.g., 'Bolsa de 1kg', 'Envase de 1L'
  institucion_id bigint references public.institucion(id) on delete set null, -- Optional: owner/origin institution
  categoria_id bigint references public.categoria(id) on delete restrict not null,
  subcategoria_id bigint references public.subcategoria(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create trigger update_producto_updated_at
  before update on public.producto
  for each row execute function public.update_updated_at_column();

-- 10. Producto Codigo Table (A product can have multiple barcodes)
create table public.producto_codigo (
  id bigint generated by default as identity primary key,
  producto_id bigint references public.producto(id) on delete cascade not null,
  codigo text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create trigger update_producto_codigo_updated_at
  before update on public.producto_codigo
  for each row execute function public.update_updated_at_column();

-- 11. Movimiento Table (Tracks transfers between institutions, quantities and units)
create table public.movimiento (
  id bigint generated by default as identity primary key,
  producto_id bigint references public.producto(id) on delete restrict not null,
  cantidad numeric not null check (cantidad > 0),
  unidad text not null, -- E.g., 'kg', 'unidades', 'paquetes'
  institucion_origen_id bigint references public.institucion(id) on delete restrict, -- Null if external entry
  institucion_destino_id bigint references public.institucion(id) on delete restrict, -- Null if external exit
  tipo_movimiento_id bigint references public.tipo_movimiento(id) on delete restrict not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint check_different_institutions check (
    institucion_origen_id is null or 
    institucion_destino_id is null or 
    institucion_origen_id <> institucion_destino_id
  )
);


-- 10. Vehiculo Table
create table public.vehiculo (
  id bigint generated by default as identity primary key,
  placa text not null unique,
  modelo text not null,
  marca text,
  color text,
  capacidad_carga text, -- Ej: '3 Toneladas', 'NPR', etc.
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create trigger update_vehiculo_updated_at
  before update on public.vehiculo
  for each row execute function public.update_updated_at_column();

-- 11. Chofer Table
create table public.chofer (
  id bigint generated by default as identity primary key,
  cedula text not null unique,
  nombre text not null,
  apellido text not null,
  telefono text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create trigger update_chofer_updated_at
  before update on public.chofer
  for each row execute function public.update_updated_at_column();


create trigger update_movimiento_updated_at
  before update on public.movimiento
  for each row execute function public.update_updated_at_column();

-- 12. Usuarios Table (profiles linked to auth.users)
create table public.usuarios (
  id uuid references auth.users(id) on delete cascade primary key,
  username text unique not null,
  nombre text not null,
  apellido text not null,
  telefono text,
  rol text not null default 'operador' check (rol in ('super_admin', 'admin', 'operador')),
  activo boolean not null default true,
  institucion_id bigint references public.institucion(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create trigger update_usuarios_updated_at
  before update on public.usuarios
  for each row execute function public.update_updated_at_column();

-- 13. Security Policies (RLS)
-- Enables Row Level Security for all tables
alter table public.estado enable row level security;
alter table public.municipio enable row level security;
alter table public.parroquia enable row level security;
alter table public.categoria enable row level security;
alter table public.subcategoria enable row level security;
alter table public.institucion enable row level security;
alter table public.tipo_movimiento enable row level security;
alter table public.producto enable row level security;
alter table public.producto_codigo enable row level security;
alter table public.vehiculo enable row level security;
alter table public.chofer enable row level security;
alter table public.movimiento enable row level security;
alter table public.usuarios enable row level security;

-- Public read policies
create policy "Allow public read" on public.estado for select using (true);
create policy "Allow public read" on public.municipio for select using (true);
create policy "Allow public read" on public.parroquia for select using (true);
create policy "Allow public read" on public.categoria for select using (true);
create policy "Allow public read" on public.subcategoria for select using (true);
create policy "Allow public read" on public.institucion for select using (true);
create policy "Allow public read" on public.tipo_movimiento for select using (true);
create policy "Allow public read" on public.producto for select using (true);
create policy "Allow public read" on public.producto_codigo for select using (true);
create policy "Allow public read" on public.vehiculo for select using (true);
create policy "Allow public read" on public.chofer for select using (true);
create policy "Allow public read" on public.movimiento for select using (true);

-- User-specific policies (authenticated users see/update only their own profile)
create policy "Users view own profile" on public.usuarios for select using (auth.uid() = id);
create policy "Users insert own profile" on public.usuarios for insert with check (auth.uid() = id);
create policy "Users update own profile" on public.usuarios for update using (auth.uid() = id);

-- Public write policies for transactions
create policy "Allow public insert" on public.movimiento for insert with check (true);
create policy "Allow public insert" on public.producto for insert with check (true);
create policy "Allow public insert" on public.producto_codigo for insert with check (true);
create policy "Allow public insert" on public.categoria for insert with check (true);
create policy "Allow public insert" on public.subcategoria for insert with check (true);
create policy "Allow public insert" on public.institucion for insert with check (true);
create policy "Allow public insert" on public.estado for insert with check (true);
create policy "Allow public insert" on public.municipio for insert with check (true);
create policy "Allow public insert" on public.parroquia for insert with check (true);
create policy "Allow public insert" on public.vehiculo for insert with check (true);
create policy "Allow public insert" on public.chofer for insert with check (true);
create policy "Allow public insert" on public.tipo_movimiento for insert with check (true);

-- Public update policies for transactions
create policy "Allow public update" on public.categoria for update using (true) with check (true);
create policy "Allow public update" on public.subcategoria for update using (true) with check (true);
-- create policy "Allow public update" on public.institucion for update using (true) with check (true);
-- create policy "Allow public update" on public.estado for update using (true) with check (true);
-- create policy "Allow public update" on public.municipio for update using (true) with check (true);
-- create policy "Allow public update" on public.parroquia for update using (true) with check (true);
-- create policy "Allow public update" on public.tipo_movimiento for update using (true) with check (true);
-- create policy "Allow public update" on public.producto for update using (true) with check (true);
-- create policy "Allow public update" on public.producto_codigo for update using (true) with check (true);
-- create policy "Allow public update" on public.movimiento for update using (true) with check (true);

-- Public delete policies for transactions
create policy "Allow public delete" on public.categoria for delete using (true);
create policy "Allow public delete" on public.subcategoria for delete using (true);
-- create policy "Allow public delete" on public.institucion for delete using (true);
-- create policy "Allow public delete" on public.estado for delete using (true);
-- create policy "Allow public delete" on public.municipio for delete using (true);
-- create policy "Allow public delete" on public.parroquia for delete using (true);
-- create policy "Allow public delete" on public.tipo_movimiento for delete using (true);
-- create policy "Allow public delete" on public.producto for delete using (true);
-- create policy "Allow public delete" on public.producto_codigo for delete using (true);
-- create policy "Allow public delete" on public.movimiento for delete using (true);

-- 14. Seed Initial Geography, Categories and Movement Types
-- Full geo seed in scripts/seed_geo.sql (24 estados, 335 municipios, 1138 parroquias)
-- Run scripts/seed_geo.sql via Supabase SQL Editor to populate/replace geo data
insert into public.estado (nombre) values 
('DISTRITO CAPITAL'),
('MIRANDA'),
('ZULIA')
on conflict (nombre) do nothing;

insert into public.municipio (nombre, estado_id) values
('LIBERTADOR', (select id from public.estado where nombre = 'DISTRITO CAPITAL')),
('CHACAO', (select id from public.estado where nombre = 'MIRANDA')),
('MARACAIBO', (select id from public.estado where nombre = 'ZULIA'))
on conflict (nombre, estado_id) do nothing;

insert into public.parroquia (nombre, municipio_id) values
('CATEDRAL', (select id from public.municipio where nombre = 'LIBERTADOR' and estado_id = (select id from public.estado where nombre = 'DISTRITO CAPITAL'))),
('CHACAO', (select id from public.municipio where nombre = 'CHACAO' and estado_id = (select id from public.estado where nombre = 'MIRANDA'))),
('OLEGARIO VILLALOBOS', (select id from public.municipio where nombre = 'MARACAIBO' and estado_id = (select id from public.estado where nombre = 'ZULIA')))
on conflict (nombre, municipio_id) do nothing;

-- Geo indexes
create index if not exists idx_municipio_estado on public.municipio(estado_id, nombre);
create index if not exists idx_parroquia_municipio on public.parroquia(municipio_id, nombre);

-- Helper: full geo chain for institutions
create or replace function public.get_institucion_geo(p_institucion_id bigint)
returns table (
  institucion_nombre text,
  direccion text,
  parroquia text,
  municipio text,
  estado text
) language plpgsql stable as $$
begin
  return query
    select i.nombre, i.direccion, p.nombre, m.nombre, e.nombre
    from public.institucion i
    join public.parroquia p on p.id = i.parroquia_id
    join public.municipio m on m.id = p.municipio_id
    join public.estado e on e.id = m.estado_id
    where i.id = p_institucion_id;
end;
$$;

insert into public.categoria (nombre) values
('Nutrición y alimentos'),
('Salud y Farmacia'),
('Higiene y sanitarios'),
('Refugio'),
('Textil y vestimenta')
on conflict (nombre) do nothing;

insert into public.tipo_movimiento (nombre) values
('Entrada'),
('Salida')
on conflict (nombre) do nothing;
