-- 1. Automatic Timestamp Trigger
create or replace function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- 2. Estado Table
create table public.estado (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create trigger update_estado_updated_at
  before update on public.estado
  for each row execute function public.update_updated_at_column();

-- 3. Municipio Table
create table public.municipio (
  id bigint generated by default as identity primary key,
  nombre text not null,
  estado_id bigint references public.estado(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (nombre, estado_id)
);

create trigger update_municipio_updated_at
  before update on public.municipio
  for each row execute function public.update_updated_at_column();

-- 4. Parroquia Table
create table public.parroquia (
  id bigint generated by default as identity primary key,
  nombre text not null,
  municipio_id bigint references public.municipio(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (nombre, municipio_id)
);

create trigger update_parroquia_updated_at
  before update on public.parroquia
  for each row execute function public.update_updated_at_column();

-- 5. Categoria Table
create table public.categoria (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create trigger update_categoria_updated_at
  before update on public.categoria
  for each row execute function public.update_updated_at_column();

-- 6. Institucion Table
create table public.institucion (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  direccion text not null,
  parroquia_id bigint references public.parroquia(id) on delete restrict not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create trigger update_institucion_updated_at
  before update on public.institucion
  for each row execute function public.update_updated_at_column();

-- 7. Tipo Movimiento Table
create table public.tipo_movimiento (
  id bigint generated by default as identity primary key,
  nombre text not null unique, -- E.g., 'Entrada', 'Salida', 'Transferencia'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create trigger update_tipo_movimiento_updated_at
  before update on public.tipo_movimiento
  for each row execute function public.update_updated_at_column();

-- 8. Producto Table
create table public.producto (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  presentacion text, -- E.g., 'Bolsa de 1kg', 'Envase de 1L'
  institucion_id bigint references public.institucion(id) on delete set null, -- Optional: owner/origin institution
  categoria_id bigint references public.categoria(id) on delete restrict not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create trigger update_producto_updated_at
  before update on public.producto
  for each row execute function public.update_updated_at_column();

-- 9. Producto Codigo Table (A product can have multiple barcodes)
create table public.producto_codigo (
  id bigint generated by default as identity primary key,
  producto_id bigint references public.producto(id) on delete cascade not null,
  codigo text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create trigger update_producto_codigo_updated_at
  before update on public.producto_codigo
  for each row execute function public.update_updated_at_column();

-- 10. Movimiento Table (Tracks transfers between institutions, quantities and units)
create table public.movimiento (
  id bigint generated by default as identity primary key,
  producto_id bigint references public.producto(id) on delete restrict not null,
  cantidad numeric not null check (cantidad > 0),
  unidad text not null, -- E.g., 'kg', 'unidades', 'paquetes'
  institucion_origen_id bigint references public.institucion(id) on delete restrict, -- Null if external entry
  institucion_destino_id bigint references public.institucion(id) on delete restrict, -- Null if external exit
  tipo_movimiento_id bigint references public.tipo_movimiento(id) on delete restrict not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint check_different_institutions check (
    institucion_origen_id is null or 
    institucion_destino_id is null or 
    institucion_origen_id <> institucion_destino_id
  )
);

create trigger update_movimiento_updated_at
  before update on public.movimiento
  for each row execute function public.update_updated_at_column();

-- 11. Security Policies (RLS)
-- Enables Row Level Security for all tables
alter table public.estado enable row level security;
alter table public.municipio enable row level security;
alter table public.parroquia enable row level security;
alter table public.categoria enable row level security;
alter table public.institucion enable row level security;
alter table public.tipo_movimiento enable row level security;
alter table public.producto enable row level security;
alter table public.producto_codigo enable row level security;
alter table public.movimiento enable row level security;

-- Public read policies
create policy "Allow public read" on public.estado for select using (true);
create policy "Allow public read" on public.municipio for select using (true);
create policy "Allow public read" on public.parroquia for select using (true);
create policy "Allow public read" on public.categoria for select using (true);
create policy "Allow public read" on public.institucion for select using (true);
create policy "Allow public read" on public.tipo_movimiento for select using (true);
create policy "Allow public read" on public.producto for select using (true);
create policy "Allow public read" on public.producto_codigo for select using (true);
create policy "Allow public read" on public.movimiento for select using (true);

-- Public write policies for transactions
create policy "Allow public insert" on public.movimiento for insert with check (true);
create policy "Allow public insert" on public.producto for insert with check (true);
create policy "Allow public insert" on public.producto_codigo for insert with check (true);
