-- ============================================================
-- CREAR TABLAS PENDIENTES: usuarios, inventario
-- Pegar en SQL Editor de Supabase y ejecutar
-- No falla si ya existen (usa IF NOT EXISTS)
-- ============================================================

-- ============================================================
-- 1. TABLA USUARIOS (perfiles vinculados a auth.users)
-- ============================================================
create table if not exists public.usuarios (
  id uuid references auth.users(id) on delete cascade primary key,
  username text unique not null,
  nombre text not null,
  apellido text not null,
  telefono text,
  rol text not null default 'operador' check (rol in ('super_admin', 'admin', 'operador')),
  activo boolean not null default true,
  institucion_id bigint references public.institucion(id) on delete set null,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

-- Trigger updated_at
create or replace function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

drop trigger if exists update_usuarios_updated_at on public.usuarios;
create trigger update_usuarios_updated_at
  before update on public.usuarios
  for each row execute function public.update_updated_at_column();

-- RLS
alter table public.usuarios enable row level security;

drop policy if exists "Users view own profile" on public.usuarios;
create policy "Users view own profile" on public.usuarios
  for select using (auth.uid() = id);

drop policy if exists "Users insert own profile" on public.usuarios;
create policy "Users insert own profile" on public.usuarios
  for insert with check (auth.uid() = id);

drop policy if exists "Users update own profile" on public.usuarios;
create policy "Users update own profile" on public.usuarios
  for update using (auth.uid() = id);

-- ============================================================
-- 2. TABLA INVENTARIO (stock actual por producto + institución)
-- ============================================================
create table if not exists public.inventario (
  id bigint generated by default as identity primary key,
  producto_id bigint references public.producto(id) on delete cascade not null,
  institucion_id bigint references public.institucion(id) on delete cascade not null,
  cantidad numeric not null default 0 check (cantidad >= 0),
  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null,
  unique (producto_id, institucion_id)
);

drop trigger if exists update_inventario_updated_at on public.inventario;
create trigger update_inventario_updated_at
  before update on public.inventario
  for each row execute function public.update_updated_at_column();

-- RLS
alter table public.inventario enable row level security;

drop policy if exists "Allow public read" on public.inventario;
create policy "Allow public read" on public.inventario for select using (true);

drop policy if exists "Allow public insert" on public.inventario;
create policy "Allow public insert" on public.inventario for insert with check (true);

drop policy if exists "Allow public update" on public.inventario;
create policy "Allow public update" on public.inventario for update using (true);

-- ============================================================
-- 3. TRIGGER: actualizar inventario automáticamente
-- ============================================================
create or replace function public.actualizar_inventario()
returns trigger as $$
begin
  if new.tipo_movimiento_id = (select id from public.tipo_movimiento where nombre = 'Entrada') then
    -- Entrada: incrementa
    insert into public.inventario (producto_id, institucion_id, cantidad)
    values (new.producto_id, coalesce(new.institucion_destino_id, new.institucion_origen_id), new.cantidad)
    on conflict (producto_id, institucion_id)
    do update set cantidad = public.inventario.cantidad + new.cantidad, updated_at = now();
  else
    -- Salida: decrementa
    insert into public.inventario (producto_id, institucion_id, cantidad)
    values (new.producto_id, coalesce(new.institucion_origen_id, new.institucion_destino_id), -new.cantidad)
    on conflict (producto_id, institucion_id)
    do update set cantidad = greatest(public.inventario.cantidad - new.cantidad, 0), updated_at = now();
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_actualizar_inventario on public.movimiento;
create trigger trg_actualizar_inventario
  after insert on public.movimiento
  for each row execute function public.actualizar_inventario();

-- ============================================================
-- 4. ASIGNAR ROL A TU USUARIO (cambiá TU_USUARIO)
-- ============================================================
-- Descomentar y ejecutar DESPUÉS de crear un usuario desde la app
-- update public.usuarios set rol = 'super_admin' where username = 'TU_USUARIO';
