-- ============================================================
-- DESPACHOS / GUÍAS DE CARGA
-- Ejecutar UNA SOLA VEZ en el SQL Editor de Supabase
-- ============================================================

-- 1. Tabla de despachos (cabecera)
create table if not exists public.despacho (
  id bigint generated by default as identity primary key,
  institucion_origen_id bigint references public.institucion(id) on delete restrict not null,
  institucion_destino_id bigint references public.institucion(id) on delete restrict,
  transportista text not null,
  vehiculo text not null,
  placa text,
  notas text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Agregar despacho_id a movimiento
alter table public.movimiento
  add column if not exists despacho_id bigint references public.despacho(id) on delete set null;

-- 3. RLS
alter table public.despacho enable row level security;

create policy "Allow public read" on public.despacho for select using (true);
create policy "Allow public insert" on public.despacho for insert with check (true);
