create table if not exists public.voluntarios (
  id bigint generated by default as identity primary key,
  cedula text not null unique,
  nombre text not null,
  apellido text not null,
  email text not null,
  telefono text,
  disponibilidad_dias text,
  disponibilidad_hora_desde time,
  disponibilidad_hora_hasta time,
  institucion_id bigint references public.institucion(id) on delete set null,
  activo boolean not null default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

drop trigger if exists update_voluntarios_updated_at on public.voluntarios;
create trigger update_voluntarios_updated_at
  before update on public.voluntarios
  for each row execute function public.update_updated_at_column();

alter table public.voluntarios enable row level security;

drop policy if exists "Allow public insert" on public.voluntarios;
create policy "Allow public insert" on public.voluntarios for insert with check (true);

drop policy if exists "Allow public select" on public.voluntarios;
create policy "Allow public select" on public.voluntarios for select using (true);

drop policy if exists "Allow public update" on public.voluntarios;
create policy "Allow public update" on public.voluntarios for update using (true);

alter table public.voluntarios
  add column if not exists fecha_nacimiento date,
  add column if not exists genero text;
